### ISSUE TITLE
Layers explained?

### ISSUE THREAD

**Issue by squirrelboot** [dusk125/sublime-betterbookmarks#16]
I am pretty new to Sublime Text 3. I Googled sublime text 3 layers, but I didn't find anything helpful.

I am using the default recommended key-map:
- F7 - Swaps the layers backwards.
- F8 - Swaps the layers forwards.
- F9 - Moves the viewport to the previous bookmark in the current visible layer.
- F10 - Moves the viewport to the next bookmark in the current visible layer.
- F11 - Adds a single bookmark to the current visible layer.
- F12 - Removes all marks in the current visible layer.
- Shift + F12 - Removes all marks from ALL layers.

When I use F7 and F8, it doesn't seem to do anything. What are layers respective to Sublime Text 3, and how do I use them?

Thank you for any help/understanding. I am using this package because I want persistent bookmarks for my projects.

**Comment by dusk125** [comment]
So the concept of bookmark layers doesn't exist natively in Sublime Text 3, they're something I came up with to allow users to store different bookmarks for different purposes. 

So by default, there's only one layer, 'bookmarks', that uses the default Sublime Text 3 bookmark icon. You can add (or remove) layers by changing the 'layer_icons' setting in BetterBookmarks.sublime-settings; make sure to make the changes in your user settings rather than the default (if you make changes to the default, they can be overwritten by an update to BetterBookmarks). 
In the default settings file, I have a couple of examples of other layers that are commented out. If you want to try them out, just uncomment them in your settings file.

The easiest way to edit the settings of a package is to go to Preferences->Package Settings->Better Bookmarks->Settings.

Let me know if you have any other questions and welcome to Better Bookmarks (and Sublime)!

**Comment by dusk125** [comment]
@squirrelboot if you have any other questions or need more clarification, feel free to ask. Once you're satisfied with my explanation, could you close this issue?
